---

- name: install apt key (Debian)
  apt_key:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    state: present
  become: yes

- name: install VS Code apt repo (Debian)
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
  become: yes

- name: install vscode
  package:
    name: code
    state: present
  become: yes

- name: ensure vscode global config directory exists
  file:
    path: ~/.config/Code/User/
    state: directory
    mode: 0755

- name: link vscode settings.json
  file:
    src: "{{ dotfiles_folder }}/vscode/settings.json"
    dest: ~/.config/Code/User/settings.json
    state: link

- name: link vscode keybindings.json
  file:
    src: "{{ dotfiles_folder }}/vscode/keybindings.json"
    dest: ~/.config/Code/User/keybindings.json
    state: link

- name: link vscode tasks.json
  file:
    src: "{{ dotfiles_folder }}/vscode/tasks.json"
    dest: ~/.config/Code/User/tasks.json
    state: link

- name: check vscode snippets directory exists
  stat:
    path: ~/.config/Code/User/snippets/
  register: snippets_folder

- name: print snippets folder status
  debug:
    msg: "{{ snippets_folder }}"

- name: link vscode snippets
  file:
    src: "{{ dotfiles_folder }}/vscode/snippets"
    dest: ~/.config/Code/User/snippets
    state: link
    force: yes

- name: install default extensions for vscode
  shell: "code --install-extension {{ item }}"
  with_items:
    - vscodevim.vim
    - vscode-icons-team.vscode-icons
    - visualstudioexptteam.vscodeintellicode
    - dracula-theme.theme-dracula

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: install vscode docker plugins if docker is installed
  shell: "code --install-extension {{ item }}"
  with_items:
    - ms-azuretools.vscode-docker
    - ms-vscode-remote.remote-containers
  when: ansible_facts.packages['docker-ce'] is defined
