---

- name: fetch microsoft deb package to install gpg key and apt-repository
  get_url:
    url: https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb
    dest: /tmp/packages-microsoft-prod.deb
    mode: 0744

- name: install microsoft gpg-key and apt-repository
  apt:
    deb: /tmp/packages-microsoft-prod.deb
  become: yes



