---

- name: include backports repo
  include_role:
    name: backports

- name: install tmux
  apt:
    name: tmux
    state: present
    default_release: buster-backports
  become: yes

- name: set up tmux config
  file:
    src: "{{ dotfiles_folder }}/tmux/.tmux.conf"
    dest: ~/.tmux.conf
    state: link
 
