---

- name: install java
  package:
    name: 'openjdk-11-jdk'
    state: present
  become: yes


- name: set java env variables
  copy:
    src: java_env.fish
    dest: ~/bin/autoload
    mode: 0777


