---

- name: install open-vm-tools
  package:
    name: 'open-vm-tools'
    state: present
  become: yes

- name: install open-vm-tools-desktop
  package: 
    name: 'open-vm-tools-desktop'
    state: present
  become: yes

