---

- name: install fish
  package:
    name: 'fish'
    state: present
  become: true

- name: get fish path
  shell: which fish
  register: fish_path
  changed_when: false

- debug:
    msg: "fish path: {{fish_path.stdout}}"

- name: set fish as default shell
  shell: "chsh -s {{ fish_path.stdout }} {{ user }}"
  become: true

- name: create fish config folder
  file:
    path: "{{ fish_config_folder }}"
    state: directory
    mode: 0755

- name: link fish variables from dotfiles
  file:
    src: "{{ dotfiles_folder}}/fish/fish_variables"
    dest: "{{ fish_config_folder }}/fish_variables"
    state: link
    force: yes

- name: link fish config from dotfiles
  file:
    src: "{{ dotfiles_folder}}/fish/config.fish"
    dest: "{{ fish_config_folder }}/config.fish"
    state: link
    force: yes

- name: ensure ~/bin/autoload dir exists
  file:
    path: "{{ autoload_folder }}"
    state: directory
    mode: 0755
