---
- name: install git
  package:
    name: 'git'
    state: present
  become: yes

- name: setup git config file
  file:
    path: ~/.config/git
    state: directory

- name: copy config file to location
  copy:
    src: gitconfig
    dest: ~/.config/git/config
    mode: 0774
    
